apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 10.4.0
  targetNamespace: argocd
  createNamespace: true
  valuesContent: |-
    configs:
      params:
        server.insecure: true
    global:
      domain: argocd.k3s.lan
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: argocd.k3s.lan
