apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: media
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:/8/rJwVpJjrv1H1Ycdl4/PBeHED+8z2/O2AFwt95Nu8dJmQplUca1Sr9K1g=,iv:RE8mzagANOjyxooY1PGWlj8RoU/p8zsDrB7/pAJqpQU=,tag:3LWbWHgn9HsM7kXqaMORdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYnVReWxtbzZ1TUx0Q0U1
            eVpxc3FNeHJKU2x0djlDdHNpeDhkTlJHWjNFClpibXZROUlyb0Y1VzZ4bkhqLzVp
            Y1haeW42T1hjRjRxb2kvQ0d6SlZOVHcKLS0tIFJ2TVFoejg0L1FyNlZQREwrREEy
            aUNZTFIrcFFwS0Z2NkZpczNlLzBBOGMKiLuQJ5vl6zhMVymoPq2fKdXhWBfXuEAL
            N4RBwX8rNWIBzsg3xw2TOb8GVqvZ8XXzSkKJ+E/pS/00mSLO4grDOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xt6wrssyc8t3ykj4dxg9pgk0yd95lpumqvgw5jaz3hgecutcsvss8rwcd3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T16:08:50Z"
    mac: ENC[AES256_GCM,data:EK+ndSzddiqgHJy0n2ErLrl3CMAMkgMvotHxwDRJ0M7GEgY83W4a8D4FqpbE53ORKzMzcS15rHaFmohEF+DHWHQy2vJabBKluKVhOUYf9OWnRO91OKBhBebPM9yc4WJ6lZL4fu+GV0qOcP5SGZPZw3FeSXngHjDB/RBEWZNxmzs=,iv:JgA0xG/Iopa+9rTxNITFGqPVtSlFvDzERO/O7u/eFJw=,tag:eItVlC6c1kZbkWX28xminQ==,type:str]
    version: 3.13.3
