apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: media
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:7hVj46qL7cT8luTKJ9LdPo3SJgHowHR5Ou/tTx1+JJ/+n90EUt9e2LHFyPc=,iv:wTgZtU6+2AH+3cWuHcg9Fl60WXTKC6cPcupYwWE9o4U=,tag:oYDXEazqGcECOmtluXv8Kw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYnVReWxtbzZ1TUx0Q0U1
            eVpxc3FNeHJKU2x0djlDdHNpeDhkTlJHWjNFClpibXZROUlyb0Y1VzZ4bkhqLzVp
            Y1haeW42T1hjRjRxb2kvQ0d6SlZOVHcKLS0tIFJ2TVFoejg0L1FyNlZQREwrREEy
            aUNZTFIrcFFwS0Z2NkZpczNlLzBBOGMKiLuQJ5vl6zhMVymoPq2fKdXhWBfXuEAL
            N4RBwX8rNWIBzsg3xw2TOb8GVqvZ8XXzSkKJ+E/pS/00mSLO4grDOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xt6wrssyc8t3ykj4dxg9pgk0yd95lpumqvgw5jaz3hgecutcsvss8rwcd3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T19:39:22Z"
    mac: ENC[AES256_GCM,data:qp4yRbIsc12gkYpWXk9QojwiGVD1pSDQVPJdaBOvZHFOpoWlMySi8onxrNmp8ECU1GjQw3TB6iDZffU6yDEs0FL24KT3gPwntbtWKBU4D+3zP9dZiFzDnDGm6RNPIOOKJmlxZAakH9+pWpq1dLj1kx/bCpQ6xwVUqcka0Z7NoP4=,iv:+44smIa5ToTqT+V1vfUV5dmwe4obaEKDBulZvL5VLvk=,tag:SQ2PcTy3GxaoK0vMAju48w==,type:str]
    version: 3.13.3
