apiVersion: v1
kind: Secret
metadata:
    name: ksops-test
    namespace: default
stringData:
    foo: ENC[AES256_GCM,data:ZbZq,iv:zpPwpgYSYQ8dnw09OUsWAClVGk76u55wDGK01ZxQS/g=,tag:DiwIbHO+PNF0tQLt95w5dA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SVBVdVNvQ21XYld0YVJM
            SEJ2MCtSdDc2OFEybSs2ZjNFNHU4c2NKR2pFCitiMjI2bTRUNkpaanhsKzNMVC9l
            ekowaUJwRDRMS1Q2cWJ6TVpsUDRsRzAKLS0tIHlzL2pjY25TUHFGWnFSWFcvcGph
            SkdEMkZNQndLRm9ITVpTUVdPMkdZdW8Kab1XL57/f3W2qvzqVOqkw/+OZF03j+X/
            EpyRB+gTUt+maYUeKC8TEWZdlHpEkGMMAMk2KW2YVgtDaqzVe58v4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xt6wrssyc8t3ykj4dxg9pgk0yd95lpumqvgw5jaz3hgecutcsvss8rwcd3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T12:56:40Z"
    mac: ENC[AES256_GCM,data:hJ3b5i/XXIo2jCK9TEDUb+gsSbsiiAjgDzmbnKRuJRbvPwt5RaJF6m+Mss/QaY5rZeSxqX90jukROoLTrxzhH3ZT7H2XZJeyYpeKO1RaP+aVjNHvMKk6f6kbWCGBEr46IhJaU5Ko2Pq8D0+S2Zu+0wcyRuL628T9KNYQJ9MiH00=,iv:OsasMDVrtGB9t/wOucuR89X3Z7SNOUC1IVnwFj9lPMM=,tag:fdUkc8798RI+CXMvxJlNwQ==,type:str]
    version: 3.13.3
